[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP"]
ignore = []
exclude = ["out","build","dist",".venv"]

[tool.isort]
profile = "black"